import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useQuery, useSubscription, useMutation } from "@apollo/client";
import { useState, useEffect } from "react";
import { gql } from "@apollo/client";
import Todos from "../components/Todos";

const AddTodo = gql`
  mutation ($todo: todos_insert_input!) {
    insert_todos(objects: [$todo]) {
      affected_rows
    }
  }
`;
const GetTodos = gql`
  query {
    todos {
      title
      id
    }
  }
`;
export default function Home() {
  const [todoTitle, setTodoTitle] = useState("");
  const [insertTodo] = useMutation(AddTodo);
  const { data, loading, error } = useQuery(GetTodos);
  console.log(data);
  async function handleOnSubmit(event) {
    event.preventDefault();
    try {
      await insertTodo({
        variables: {
          todo: {
            title: todoTitle,
          },
        },
      });
      setTodoTitle("");
      console.log("Inserted todo");
    } catch (error) {
      console.log(error);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Create <a href="https://nextjs.org">Todos</a> with Nhost
        </h1>
        <div className={styles.searchcontainer}>
          <form onSubmit={handleOnSubmit}>
            <input
              className={styles.input}
              type="text"
              value={todoTitle}
              onChange={(event) => setTodoTitle(event.target.value)}
              placeholder="Add new todo"
            />
          </form>
        </div>
        {/* <pre>{JSON.stringify(data.todos, null, 2)}</pre> */}
        {data && data.todos && (
          <Todos todos={data.todos} error={error} loading={loading} />
        )}
      </main>
    </div>
  );
}
